development:
  adapter: mysql2
  username: root
  database: feedback_development
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  username: root
  database: feedback_test
  pool: 5
  timeout: 5000
